name:                RayTracer
version:             0.1.0.0
github:              "SimonCockx/RayTracer"
license:             BSD3
author:              "Simon Cockx"
maintainer:          "simon@sikanda.be"
copyright:           "2020 Simon Cockx"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SimonCockx/RayTracer#readme>

dependencies:
- base >= 4.7 && < 5
- massiv
- massiv-io

library:
  source-dirs: src

executables:
  RayTracer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RayTracer

tests:
  Vector-test:
    main:                VectorSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RayTracer
    - tasty
    - tasty-hunit
    - tasty-smallcheck
